version: "3"

services:
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: social-network-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  nginx:
    image: 'nginx:alpine'
    restart: unless-stopped
    tty: true
    container_name: social-network-nginx
    working_dir: /var/www
    volumes:
      - .:/var/www/
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - php
  mysql:
    image: mysql:latest
    container_name: social-network-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  node:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    tty: true
    ports:
      - "5173:5173"
    working_dir: /var/www
    volumes:
      - .:/var/www # Монтируем локальную папку в контейнер как /var/www